/**
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) Bao Project and Contributors. All rights reserved.
 */

#ifndef __PLAT_PLATFORM_H__
#define __PLAT_PLATFORM_H__

#include <drivers/zynq_uart.h>

#define PLAT_EVENT_L1D_CACHE_REFILL        0x03U
#define PLAT_EVENT_DATA_MEMORY_ACCESS      0x13U
#define PLAT_EVENT_L2D_CACHE_ACCESS        0x16U
#define PLAT_EVENT_L2D_CACHE_REFILL        0x17U
#define PLAT_EVENT_BUS_ACCESS              0x19U
#define PLAT_EVENT_EXTERNAL_MEMORY_REQUEST 0xC0U

#define PLAT_MEM_THROT_EVENT PLAT_EVENT_L1D_CACHE_REFILL

#define DATA_MEMORY_ACCESS      PLAT_EVENT_DATA_MEMORY_ACCESS
#define L2D_CACHE_ACCESS        PLAT_EVENT_L2D_CACHE_ACCESS
#define L2D_CACHE_REFILL        PLAT_EVENT_L2D_CACHE_REFILL
#define BUS_ACCESS              PLAT_EVENT_BUS_ACCESS
#define EXTERNAL_MEMORY_REQUEST PLAT_EVENT_EXTERNAL_MEMORY_REQUEST

#endif
