name: Bao component base workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/bao-container-run
        with:
          run: make gitlint GITLINT_BASE=${{ github.event.pull_request.base.sha }}
      - if: ${{ github.event_name == 'push' }}
        uses: ./.github/actions/bao-container-run
        with:
          run: make gitlint GITLINT_BASE=${{ github.event.before }}
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/bao-container-run
        with:
          run: make gitlint GITLINT_BASE=HEAD

  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/bao-container-run
        with:
          run: make license-check
