name: RISC-V Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  build-riscv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [
          "qemu-riscv64-virt",
          "qemu-riscv32-virt",
        ]
        irqc: [
          "PLIC",
          "APLIC",
          "AIA",
        ]
        ipic: [
          "IPIC_SBI",
          "IPIC_ACLINT",
        ]
        cross_compile: [
            "",
            "CROSS_COMPILE=clang",
        ]
        include:
          - platform: "qemu-riscv64-virt"
            kconfig: "QEMU_RISCV64_VIRT"
          - platform: "qemu-riscv32-virt"
            kconfig: "QEMU_RISCV32_VIRT"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/bao-container-run
        with:
          run: printf 'CONFIG_${{ matrix.kconfig }}_IRQC_${{ matrix.irqc }}=y\nCONFIG_${{ matrix.kconfig }}_${{ matrix.ipic }}=y\n'
            > configs/null/defconfig &&
            make PLATFORM=${{ matrix.platform }} CONFIG=null ${{ matrix.cross_compile }}
