name: Arm Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [
          "fvp-a",
          "fvp-a-aarch32",
          "fvp-r",
          "fvp-r-aarch32"
        ]
        gic: [
          "GICV2",
          "GICV3",
        ]
        cross_compile: [
            "",
            "CROSS_COMPILE=clang",
        ]
        include:
          - platform: "fvp-a"
            kconfig: "FVP_A"
          - platform: "fvp-a-aarch32"
            kconfig: "FVP_A_AARCH32"
          - platform: "fvp-r"
            kconfig: "FVP_R"
          - platform: "fvp-r-aarch32"
            kconfig: "FVP_R_AARCH32"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/bao-container-run
        with:
          run: printf 'CONFIG_${{ matrix.kconfig }}_${{ matrix.gic }}=y\n'
            > configs/null/defconfig &&
            make PLATFORM=${{ matrix.platform }} CONFIG=null ${{ matrix.cross_compile }}
