name: Bao Kao Testing Framework

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [
          "qemu-aarch64-virt",
          "qemu-riscv64-virt",
          "fvp-a",
          "fvp-r"
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Bao Kao tests
        uses: ./.github/actions/bao-container-run
        with:
          run: >
            git config --global url.https://github.com/.insteadOf git@github.com:
            && make tests PLATFORM=${{ matrix.platform }}
